server:
  port: 9000
  servlet:
    context-path: /verly-service
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/verly
    username: admin
    password: admin!@#$%
    type: com.zaxxer.hikari.HikariDataSource